tap "homebrew/bundle"
tap "homebrew/autoupdate"
tap "homebrew/services"
tap "homebrew/command-not-found"

brew "bash"
brew "bash-completion"
brew "binutils"
brew "curl"
brew "coreutils"
brew "diffutils"
# brew "docker" # caskのDockerと競合するのでcaskのものを使う
# brew "docker-completion"
brew "dos2unix"
brew "ffmpeg"
brew "findutils"
brew "gcc"
brew "git"
brew "gnu-sed"
brew "gnu-tar"
brew "gnu-time"
brew "gnu-which"
brew "grep"
brew "iproute2mac"
brew "jq"
brew "kubectx"
brew "kubernetes-cli"
brew "make"
brew "openssh"
brew "openssl"
brew "python"
brew "ruby"
brew "terminal-notifier"
brew "tig"
brew "tmux"
brew "tree"
brew "unar"
brew "unzip"
brew "vim"
brew "watch"
brew "wget"
brew "whois"
brew "asdf"

# optional
brew "awscli"
brew "e2fsprogs"
brew "exiftool"
brew "gnupg"
brew "gnutls"
brew "go"
brew "gptfdisk"
brew "kustomize"
brew "nmap"
# brew "nodebrew"
brew "smartmontools"
brew "socat"
brew "sqlite"
brew "tor"
brew "youtube-dl"

# cask
cask "clipy"
cask "monitorcontrol"
cask "switchresx"
cask "google-chrome"
# cask "lastpass"
cask "visual-studio-code"
cask "alacritty"
cask "slack"
# cask "gather"
cask "zoom"
cask "microsoft-remote-desktop"
cask "postman"
cask "altair-graphql-client"
cask "mysqlworkbench"
cask "docker"
cask "android-studio"
cask "microsoft-excel"
cask "microsoft-word"
cask "microsoft-powerpoint"
cask "microsoft-edge"
cask "keepassxc"

# mas
mas "Speedtest by Ookla", id: 1153157709
mas "AS Timer", id: 512464723
mas "Battery Monitor: Health, Info", id: 836505650
mas "Stickies - Sticky notes app", id: 1572061218
mas "Magnet", id: 441258766
